
platform :ios, '8.0'

use_frameworks!

target ‘swiftSkills’ do

pod 'Alamofire'
pod 'SnapKit'
pod 'SwiftyJSON'
pod 'Kingfisher'
pod 'NVActivityIndicatorView' #加载状态
pod 'DZNEmptyDataSet' #空视图
pod 'Hero' #专场动画
pod 'IQKeyboardManagerSwift' #键盘监听
pod 'Toast-Swift' #提示
#pod 'AMapLocation-NO-IDFA' #高德定位SDK
#pod 'AMapNavi-NO-IDFA' #高德导航SDK
pod 'SQLite.swift' #数据库
pod 'QRCodeReader.swift', '~> 8.2.0'
pod 'PGDatePicker', '>= 1.3.0'

#pod “BaiduMapKit” #百度地图SDK

#pod 'WechatOpenSDK'

end

